### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by MihailProcudin** [rspieker/jest-transform-svelte#29]
Hi @rspieker ,

Maybe you  know what may cause this issue ?

```
 FAIL  tests/Main.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'type' of undefined

      at node_modules/svelte/src/compiler/compile/create_module.ts:110:26
          at Array.map (<anonymous>)
      at cjs (node_modules/svelte/src/compiler/compile/create_module.ts:107:27)
      at create_module (node_modules/svelte/src/compiler/compile/create_module.ts:31:31)
      at Component.generate (node_modules/svelte/src/compiler/compile/Component.ts:344:19)
      at Object.compile (node_modules/svelte/src/compiler/compile/index.ts:88:19)
      at Object.process (node_modules/jest-transform-svelte/index.js:26:26)
```

Thanks

**Comment by MikeProcudin** [comment]
This is causing the issue, 
import 'unfetch/polyfill'
either 
import 'unfetch/polyfill'

😢 😢 😢
